package com.eggtive.spm.common.enums;

public enum ErrorCode {
    INVALID_INPUT,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    CONFLICT,
    INVALID_SCORE,
    INVALID_DATE,
    CLASS_FULL,
    INTERNAL_ERROR,
    VALIDATION_FAILED,
    INVALID_FILE_TYPE,
    FILE_TOO_LARGE,
    INVALID_FILE_CONTENT,
    STORAGE_ERROR,
    OCR_ERROR,
    UPLOAD_ALREADY_PROCESSING,
    UPLOAD_ALREADY_PROCESSED
}
