name: Deploy to Dev

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  backend:
    uses: ./.github/workflows/_deploy-backend.yml
    with:
      environment: dev
    secrets: inherit

  frontend:
    uses: ./.github/workflows/_deploy-frontend.yml
    with:
      environment: dev
      s3-bucket: spm-dev-frontend
      cloudfront-comment: spm-dev
    secrets: inherit
